### PR TITLE
fix: ensure static image map is available on first load

### LINKED ISSUE #234: $img does not return the correct url on nuxt generated pages
The `$img` function correctly generates the image on `nuxt generate` and returns the url to the generated image, but when viewing the generated page the returned url is incorrect and the image does not load.

For example the following (simplified) code in a page component:

```vue
<template>
  <div class="page-wrapper">
    <SocialHead :image="getMetaImage" />
  </div>
</template>

<script>
export default {
  computed: {
    getMetaImage() {
      const imageSrc = this.$img('https://back.wildrockmtb.com/uploads/tanc_jump_51512c7cec.jpg', { width: 1000, height: 100, quality: 65 }, { provider: 'static' })
      console.log('Generated source: ', imageSrc)
      return imageSrc
    },
  },
}
</script>
```
When running `nuxt generate` the following is shown in the output:

```
Generated source: /_nuxt/image/9014ee.jpg
```

But when viewing the generated page, console displays:

```
Generated source:  https://back.wildrockmtb.com/uploads/tanc_jump_51512c7cec.jpg
```

This is also the url passed to the `:image` prop in the generated page, which is not the `$img` generated image.

How is it possible to obtain and use the correctly generated `/_nuxt/image/***` url when using the `$img` function?

### PR DESCRIPTION
**Pull request by danielroe**
* Worth also considering whether to use `fetch` (object syntax, but would require Nuxt 2.15+) vs `data` (?)

closes #234 

Likely also addresses https://github.com/nuxt/image/issues/167#issuecomment-826439905, https://github.com/nuxt/image/issues/215#issuecomment-826449532

### CODE REVIEW

File: src/runtime/image.ts [hunk 1]
```diff
@@ -40,8 +40,9 @@ export function createImage (globalOptions: CreateImageOptions, nuxtContext: any
 
       if (process.server) {
         const { ssrContext } = ctx.nuxtContext
+        const ssrState = ssrContext.nuxt
         const ssrData = ssrContext.nuxt.data[0]
```
Comment (pi0) [inline src/runtime/image.ts:44]: we can refactor this 🙈

**Review by pi0 — APPROVED** [review]

**Comment by tanc** [comment]
Confirmed that with these applied changes the client now gets the correct mapping returned. Thanks!
