### PR TITLE
fix(nuxt-picture): allow `data-*` in imgAttrs

### LINKED ISSUE #2013: data-* does not exist in type ImgHTMLAttributes
First of all: Thank you for the great typescript update in v2.0 🥳 

I discoverd a typescript issue when trying to add a data attribute to `img-attrs` for `<NuxtPicture />`

Example:
```vue
<nuxt-picture
  :src="src"
  :img-attrs="{
    'data-test': 'test',
  }" />
```

Produces following TS Error:

Image

### PR DESCRIPTION
**Pull request by dreitzner**
### 🔗 Linked issue

resolves #2013 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This fixes a typescript issue, that would give a typescript error when passing a `data-*` to NuxtImage imgAttrs prop.

### CODE REVIEW

File: src/runtime/components/NuxtPicture.vue [hunk 1]
```diff
@@ -32,13 +32,14 @@ import { markFeatureUsage } from '../utils/performance'
...
 import type { BaseImageProps } from '../utils/props'
+import type { DataAttributes } from '../../types/image'
 import type { ConfiguredImageProviders, ProviderDefaults } from '@nuxt/image'
 
 import { useHead, useNuxtApp, useRequestEvent } from '#imports'
 
 export interface PictureProps<Provider extends keyof ConfiguredImageProviders> extends BaseImageProps<Provider> {
   legacyFormat?: string
-  imgAttrs?: ImgHTMLAttributes
+  imgAttrs?: ImgHTMLAttributes & DataAttributes
```
Comment (danielroe) [inline src/runtime/components/NuxtPicture.vue:42]: I think Vue itself might expose the types we need here

we did something similar for NuxtLink recently

Comment (dreitzner) [reply src/runtime/components/NuxtPicture.vue:42]: This was the first place I looked, but I couldn't find the correct type.

image


In NuxtLink I see a type used from vue-router, but that would not be applicable I think.

**Comment by danielroe** [comment]
thank you! :heart:
