### PR TITLE
fix: apply preset sizes when component sizes prop is undefined

### LINKED ISSUE #1918: Preset sizes not applied when component sizes prop is undefined
### Description
When using image presets with defined `sizes` in `nuxt.config.ts`, the preset sizes are not applied if the component's `sizes` prop is `undefined`. This causes the image to fallback to density-based srcset (`1x, 2x`) instead of the expected width-based srcset (`320w, 640w, etc.`), leading to incorrect image serving.

### Reproduction
```ts
// nuxt.config.ts
export default defineNuxtConfig({
  image: {
    presets: {
      responsive: {
        sizes: '100vw sm:50vw md:400px'
      }
    }
  }
})
```

```vue
<!-- Component usage -->
<NuxtImg 
  src="/image.png" 
  preset="responsive"
  :sizes="undefined"  // or simply omitted
  width="300" 
  height="400" 
/>

### PR DESCRIPTION
**Pull request by tyminko**
## 🔧 Fix

Fixes #1918

### Problem
When using image presets with defined `sizes`, the preset sizes are not applied if the component's `sizes` prop is `undefined`. This causes fallback to density-based srcset instead of the expected width-based srcset from presets.

### Changes Made

1. **Enhanced `getSizes` function** (`src/runtime/image.ts`):
   - Added proper preset merging using `defu` 
   - Ensures preset `sizes` and `densities` are used when not overridden by component props

2. **Updated components** (`NuxtImg.vue`, `NuxtPicture.vue`):
   - Only pass `sizes` and `densities` props when explicitly defined (`!== undefined`)
   - Prevents `undefined` from overriding preset values

3. **Added tests**:
   - Test for preset sizes application when component sizes is undefined
   - Test for preset densities application when component densities is undefined

### Before vs After

**Before**: `/_ipx/s_300x400/image.png 1x, /_ipx/s_600x800/image.png 2x` (density-based)  
**After**: `/_ipx/s_320x427/image.png 320w, /_ipx/s_640x853/image.png 640w, /_ipx/s_1024x1365/image.png 1024w` (width-based from preset)

### Testing
- ✅ All existing tests pass (26/26 image tests)
- ✅ New tests verify the fix works correctly
- ✅ Linting passes (`pnpm lint`)
- ✅ Build succeeds (`pnpm build`)
- ✅ No regressions in core functionality

### Breaking Changes
None. This is a bug fix that makes the behavior match the documented/expected behavior.

### CODE REVIEW

File: src/runtime/components/NuxtPicture.vue [hunk 1]
```diff
@@ -110,8 +110,8 @@ const sources = computed<Source[]>(() => {
   return formats.map((format) => {
     const { srcset, sizes, src } = $img.getSizes(props.src!, {
       ...providerOptions.value,
-      sizes: props.sizes || $img.options.screens,
```
Comment (danielroe) [inline src/runtime/components/NuxtPicture.vue:113]: it looks like we lose this behaviour - should we pass `screens` as a fallback in `getSizes`?

File: test/nuxt/picture.test.ts [hunk 2]
```diff
@@ -65,7 +65,7 @@ describe('Renders simple image', () => {
...
+        <source type="image/webp" srcset="/_ipx/f_webp&amp;s_200x200/image.png 1x, /_ipx/f_webp&amp;s_400x400/image.png 2x"><img width="200" height="200" data-nuxt-pic="" src="/_ipx/f_png&amp;s_400x400/image.png" srcset="/_ipx/f_png&amp;s_200x200/image.png 1x, /_ipx/f_png&amp;s_400x400/image.png 2x">
```
Comment (danielroe) [inline test/nuxt/picture.test.ts]: added a test to show that omitting `$img.screens` changes behaviour
