### PR TITLE
fix(hygraph): prevent broken image urls

### LINKED ISSUE #1998: Hygraph provider produces broken URLs when no transformation is requested
## Description

When using the hygraph-provider to show images, providing no transformations will return a broken image URL, resulting in the image not being displayed at all.

## Reproduction

[Stackblitz minimal reproduction](https://stackblitz.com/edit/nuxt-starter-kwyc2mxi?file=app.vue)

```ts
// nuxt.config.ts
export default defineNuxtConfig({
  modules: ['@nuxt/image'],
  image: {
    hygraph: {
      baseURL: 'https://eu-west-2.graphassets.com/cma6x4vl1007901w50aelaqrj',
    },
  },
});
```

```vue
<template>
  <div>
    <NuxtImg
      src="https://eu-west-2.graphassets.com/cma6x4vl1007901w50aelaqrj/aMvQyQbdSk6obGfhMJJG"
      provider="hygraph"
    />
  </div>
</template>
```

* Resulting URL: `https://eu-west-2.graphassets.com/cma6x4vl1007901w50aelaqrj/resize=/auto_image/aMvQyQbdSk6obGfhMJJG`
* Expected URL: `https://eu-west-2.graphassets.com/cma6x4vl1007901w50aelaqrj/auto_image/aMvQyQbdSk6obGfhMJJG`

### PR DESCRIPTION
**Pull request by screeny05**
The hygraph connector now only adds optimizations to the url if they are requested.

### 🔗 Linked issue

Fixes #1998 

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This fix modifies the hygraph provider to ensure no broken URLs are being returned from it. Specifically, the hygraph asset transformation API does not accept an empty `resize` parameter in the URL. Calling the provider without a transform will build a URL like this:

```
https://eu-west-2.graphassets.com/<baseId>/resize=/auto_image/<imageId>
```

That is wrong, as hygraph expects the `resize=` parameter to have at least `width` or `height` values. Otherwise it will throw a `Bad Request` error response.

This PR only adds the parameter, when there's a transformation going on.

### CODE REVIEW

File: src/runtime/providers/hygraph.ts [hunk 1]
```diff
@@ -69,7 +69,11 @@ function optimizeHygraphImage(baseURL: string, url: string, optimizations: Image
     }
   }
 
-  const optim = `${optimBase}=${optimList.join(',')}`
+  if (optimList.length === 0) {
+    return joinURL(baseURL, baseId, quality, imageFormat, imageId)
+  }
+
+  const optim = `${optimBase}=${optimList.join(',')}`;
```
Comment (danielroe) [inline src/runtime/providers/hygraph.ts]:
```suggestion
  const optim = `${optimBase}=${optimList.join(',')}`
```

**Comment by screeny05** [comment]
Just fixed the failing test
