### PR TITLE
fix(bunny): merge query params with existing image src

### LINKED ISSUE #2055: bunny provider: can't handle src urls with query params
Bunny image provider can't handle URLs with query params correctly:

src: https://example.com?foobar

Result of bunny image provider: https://example.com?foobar?quality=80

Expected: https://example.com?foobar&quality=80

### PR DESCRIPTION
**Pull request by infabo**
In case the image src already contains a query parameter, it is necessary to properly add bunny query params. This is accomplished using withQuery helper from ufo.

### 🔗 Linked issue

resolves #2055

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

In case the image src already contains a query parameter, it is necessary to properly add bunny query params. This is accomplished using withQuery helper from ufo.

e.g. url is http://example.com/image.jpg?timestamp

### CODE REVIEW

File: src/runtime/providers/bunny.ts [hunk 1]
```diff
@@ -1,9 +1,8 @@
-import { joinURL } from 'ufo'
-import { createOperationsGenerator } from '../utils/index'
+import { withBase, withQuery } from 'ufo'
+import { createMapper } from '../utils/index'
 import { defineProvider } from '../utils/provider'
 
-const operationsGenerator = createOperationsGenerator({
-  keyMap: {
+const operationsGenerator = createMapper({
```
Comment (danielroe) [inline src/runtime/providers/bunny.ts]: is there a reason you changed this? I think it's causing the type checking errors below

Comment (infabo) [reply src/runtime/providers/bunny.ts]: Because `withQuery` needs an mapped object instead of a concatenated query string.
